# Generated by Django 4.1.4 on 2023-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
